### ISSUE TITLE
Email Validation on the client side for syntactical errors and on the server side to test the validity

### ISSUE THREAD

**Issue by Coder-Srinivas** [fave77/pbchess#54]
**Is your feature request related to a problem? Please describe.** :bulb:
The website lacks the feature of validating emails, when a user registers without using google.

**Describe the solution you'd like** :sparkles:
I would like to add email validation to the website whenever a user registers using the npm deep-email-validator module on the client side.

**Comment by fave77** [comment]
@Coder-Srinivas Your suggested package only provides email-validation. Since, a rudimentary hard-coded validation already exists on the client side and your last PR included sending emails while registering, we need an `Email Verification` feature.

Have a look at this [article](https://soshace.com/verifying-an-email-address-without-sending-an-email-in-nodejs/)!

**Comment by Coder-Srinivas** [comment]
@fave77 We can remove the hard-coded validation and use the deep-email-validator on the client side to verify the authenticity of the email. If the email is syntactically correct, we can send it to the backend which will send the client a dummy email to check for it's authenticity.
