### ISSUE TITLE
Contact us Section .

### ISSUE THREAD

**Issue by RubenFalcao14** [fave77/pbchess#81]
The site does not have a contact us section. So if a person if facing any issues then he cannot report it.

I would like to add the contact us section.

**Comment by RubenFalcao14** [comment]
I'm a GSSOC'21 participant and I would love to work on it.
Thank You.

**Comment by adi-g15** [comment]
@RubenFalcao14 It is not actually needed, that's why this was closed. There is a already a link to github in the footer, where we manage all bug reports (this issues section).
Though thanks to your suggestion, we may be changing it from Support Us to report an issue or something similar 👍
It may not have been an issue to be worked upon, but your suggestion was considered 🙂
